name = "cadvisor"
description = "Analyzes resource usage and performance characteristics of running containers"
category = "monitoring"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/cadvisor.png"

[[versions]]
version = "latest"
image = "gcr.io/cadvisor/cadvisor:latest"
default = true

[volumes]
rootfs = "/rootfs"
var_run = "/var/run"
sys = "/sys"
var_lib_docker = "/var/lib/docker"

[ports]
main = 8080
