name = "mariadb"
description = "Community-developed fork of MySQL, drop-in replacement"
category = "database"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/mariadb.png"

[[versions]]
version = "11"
image = "mariadb:11"
default = true

[[versions]]
version = "10"
image = "mariadb:10"

[env]
MARIADB_ROOT_PASSWORD = { description = "Root password", required = true, default_value = "bosun" }
MARIADB_DATABASE = { description = "Default database name", required = false, default_value = "{name}" }
MARIADB_USER = { description = "Additional user", required = false }
MARIADB_PASSWORD = { description = "Additional user password", required = false }

[volumes]
data = "/var/lib/mysql"

[ports]
main = 3306
