name = "minio"
description = "High-performance, S3-compatible object storage"
category = "storage"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/minio.png"

[[versions]]
version = "latest"
image = "minio/minio:latest"
default = true

[env]
MINIO_ROOT_USER = { required = false, default_value = "minioadmin" }
MINIO_ROOT_PASSWORD = { required = false, default_value = "minioadmin" }

[volumes]
data = "/data"

[ports]
main = 9000
console = 9001
